# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:

  postgres:
    image: postgres:17
    container_name: postgresdb
    environment:
      POSTGRES_DB: bankrest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
